### PR TITLE
Remove python 3.11 dependencies

### PR DESCRIPTION
**Pull request by JaurbanRH**
strbool is deprecated in new version of python.

### CODE REVIEW

**Comment by pestanko** [comment]
I would create a new function for conversion, something like:
```python
def str2bool(v: str) -> bool:
  return str(v).lower() in ("yes", "true", "t", "1", "on")
```

**Review by dhlavac — DISMISSED** [review]

**Review by mdujava — APPROVED** [review]

**Review by mdujava — APPROVED** [review]

**Comment by mkudlej** [comment]
FYI. workflows https://github.com/3scale-qe/3scale-api-python/tree/master/.github/workflows should be changed and tested with are locked to Python 3.11 and I think they should be checked with newer Python before this PR is merged.

**Review by mkudlej — CHANGES_REQUESTED** [review]
Check workflows and Python 3.12 availability in Linux image which is used in workflows.

**Comment by dhlavac** [comment]
@JaurbanRH as @mkudlej mention, please check and change version in workflow files

**Comment by mdujava** [comment]
As I remember we do not want to upgrade to 3.12 yet, this code works for 3.11 and 3.12, so should be fine to merge as is.

**Review by dhlavac — APPROVED** [review]

**Comment by dhlavac** [comment]
@mkudlej can we merge it ? Tried with 3.11 and 3.12 should be working with both versions and image will be created with 3.11

**Review by mkudlej — APPROVED** [review]

**Pull request merged**
